### PR TITLE
feat: add custom memos url #1

### PR DESCRIPTION
**Pull request by CorrectRoadH**
Implement the feature to custom the memos server;

telegram-cloud-photo-size-5-6197081240952222823-y

CleanShot 2023-04-19 at 23 11 12@2x

### CODE REVIEW

**Comment by shwangdev** [comment]
Any one who is working on this PR?

**Comment by CorrectRoadH** [comment]
> Any one who is working on this PR?

I send the email to author of the software very very long ago. He tell me that he will merge it in next week. But The PR still not be merged.🥲

**Comment by sheldon123z** [comment]
please just merge and release this version

**Comment by shwangdev** [comment]
who can merge PR?

**Comment by shwangdev** [comment]
@CorrectRoadH  感觉作者没精力时间搞这个，你不如基于这个PR 做个release, 我去下载安装。

**Pull request merged**
